### ISSUE TITLE
following `README.md` and code does not compile, error log is attached - org.webjars.npm#js-tokens not found

### ISSUE THREAD

**Issue by jhegedus42** [chandu0101/scalajs-react-template#11]
```
Jozsefs-MacBook-Pro:scalajs-react-template joco$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
Jozsefs-MacBook-Pro:scalajs-react-template joco$ ls
LICENSE         README.md       build.sbt       index.html      project         src             target
Jozsefs-MacBook-Pro:scalajs-react-template joco$ cat README.md
scalajs-react-template
======================


### Launch this project:

1. clone the project

2. In the project directory run:
`sbt fastOptJS`

3. On your browser go to:
http://localhost:12345/index.htmlJozsefs-MacBook-Pro:scalajs-react-template joco$ date
Fri Dec  7 08:01:06 EET 2018
Jozsefs-MacBook-Pro:scalajs-react-template joco$ sbt
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/joco/dev/IM/im-2018jan/_inspirations/scalajs-react-template/project
[info] Loading settings from build.sbt ...
[info] Set current project to scalajs-react-template (in build file:/Users/joco/dev/IM/im-2018jan/_inspirations/scalajs-react-template/)
[info] sbt server started at local:///Users/joco/.sbt/1.0/server/220f33af74428a557e53/sock
sbt:scalajs-react-template> compile
[info] Updating ...
[INFO] [12/07/2018 08:01:28.451] [Workbench-System-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(Workbench-System)] Server online at http://localhost:12345/
[warn]  module not found: org.webjars.npm#js-tokens;[3.0.0,4),[4.0.0,5)
[warn] ==== local: tried
[warn]   /Users/joco/.ivy2/local/org.webjars.npm/js-tokens/[3.0.0,4),[4.0.0,5)/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/webjars/npm/js-tokens/[3.0.0,4),[4.0.0,5)/js-tokens-[3.0.0,4),[4.0.0,5).pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.webjars.npm#js-tokens;[3.0.0,4),[4.0.0,5): not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          org.webjars.npm:js-tokens:[3.0.0,4),[4.0.0,5)
[warn]            +- org.webjars.npm:loose-envify:[1.1.0,2)
[warn]            +- org.webjars.npm:react:16.2.0 ((org.scalajs.sbtplugin.ScalaJSPluginInternal.scalaJSDependenciesSettings) ScalaJSPluginInternal.scala#L1099)
[warn]            +- default:scalajs-react-template_sjs0.6_2.12:1.0
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.webjars.npm#js-tokens;[3.0.0,4),[4.0.0,5): not found
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2381)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:745)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: org.webjars.npm#js-tokens;[3.0.0,4),[4.0.0,5): not found
[error] Total time: 4 s, completed Dec 7, 2018 8:01:31 AM
```

**Comment by jhegedus42** [comment]
should I nuke `.ivy2` or `.sbt` ?

**Comment by jhegedus42** [comment]
ok, i hacked it into [my toy-code](https://github.com/jhegedus42/IM_shared_2018_11_22/blob/384165d650012fb8a043bc7bf27b591956f12f0a/layer_V_JS_client/src/main/scala/demo/app/App.scala#L21
)
the result does not look the best, but seem to be functional (possibly I need to do some css magic) : 

![image](https://user-images.githubusercontent.com/6671476/49687387-b33a7e80-fb0a-11e8-88ee-823f10613e16.png)
